app:
  version: 1.0.0

server:
  port: 9999

#Below are needed property for Spring appliction talking with MySQL DB.
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/conference_demo
    url: ${DB_URL}
    username: ${db_username}
    password: ${db_password}
#   Below username and password is for heroku
#   username: jqgorenofqvdhi
#   password: 463af22b05fbed1373aa1d1e5ecd7809d070bff35e047fc0cba8356f898db32f
#    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 8
      max-total: 20
      pool-prepared-statements: true
  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: ${db_dialect}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jdbc:
        lob:
          non_contextual_creation: true
    generate-ddl: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
